[package]
name = "todo_lib"
version = "1.0.1"
authors = ["Vladimir Markelov <vmatroskin@gmail.com>"]
edition = "2018"
keywords = ["todotxt"]
license = "MIT"
description = "Collection of utilities for todo.txt format"
readme = "README.md"
repository = "https://github.com/VladimirMarkelov/todo_lib"

[dependencies]
regex = "1.0.0"
chrono = "^0.4"
caseless = "0.2.1"
failure="0.1.3"

[dependencies.todo-txt]
version = "2.0"
features = ["extended"]
